# Generated by Django 4.1 on 2022-09-15 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internationaleregler", "0002_racismpoint_date_posted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="racismpoint",
            name="title",
        ),
        migrations.AlterField(
            model_name="racismpoint",
            name="description",
            field=models.CharField(
                help_text="Hvad sagde/gjorde personen", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="racismpoint",
            name="points",
            field=models.IntegerField(
                help_text="Hvor mange point får personen. Sæt minus foran hvis du vil give negative point"
            ),
        ),
        migrations.AlterField(
            model_name="racismpoint",
            name="user",
            field=models.ForeignKey(
                help_text="Hvem sagde/gjorde det",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
